# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from path import *
import DxLogin as dl
import traceback
import err
import tweet
import os,time
import json
from threading import Thread
try:
    class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
            MainWindow.setObjectName("MainWindow")
            MainWindow.resize(940, 716)
            font = QtGui.QFont()
            font.setFamily("Microsoft YaHei UI")
            MainWindow.setFont(font)
            self.centralwidget = QtWidgets.QWidget(MainWindow)
            self.centralwidget.setObjectName("centralwidget")
            self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
            self.verticalLayout_3.setObjectName("verticalLayout_3")
            self.label = QtWidgets.QLabel(self.centralwidget)
            font = QtGui.QFont()
            font.setPointSize(28)
            self.label.setFont(font)
            self.label.setObjectName("label")
            self.verticalLayout_3.addWidget(self.label)
            self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
            self.horizontalLayout_2.setObjectName("horizontalLayout_2")
            self.label_2 = QtWidgets.QLabel(self.centralwidget)
            self.label_2.setObjectName("label_2")
            self.horizontalLayout_2.addWidget(self.label_2)
            self.pushButton = QtWidgets.QPushButton(self.centralwidget)
            self.pushButton.setObjectName("pushButton")
            self.tweetb=QtWidgets.QPushButton(self.centralwidget)
            self.tweetb.setObjectName("tweetb")
            self.horizontalLayout_2.addWidget(self.pushButton)
            self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
            self.pushButton_10.setObjectName("pushButton_10")
            self.horizontalLayout_2.addWidget(self.pushButton_10)
            spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
            self.horizontalLayout_2.addItem(spacerItem)
            self.horizontalLayout_2.addWidget(self.tweetb)
            self.verticalLayout_3.addLayout(self.horizontalLayout_2)
            self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
            self.tabWidget.setObjectName("tabWidget")
            self.tab_2 = QtWidgets.QWidget()
            self.tab_2.setObjectName("tab_2")
            self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_2)
            self.verticalLayout.setObjectName("verticalLayout")
            self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
            self.horizontalLayout_4.setObjectName("horizontalLayout_4")
            self.label_3 = QtWidgets.QLabel(self.tab_2)
            self.label_3.setObjectName("label_3")
            self.horizontalLayout_4.addWidget(self.label_3)
            spacerItem1 = QtWidgets.QSpacerItem(218, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
            self.horizontalLayout_4.addItem(spacerItem1)
            self.reload = QtWidgets.QToolButton(self.tab_2)
            self.reload.setObjectName("reload")
            self.horizontalLayout_4.addWidget(self.reload)
            self.toolButton = QtWidgets.QToolButton(self.tab_2)
            self.toolButton.setObjectName("toolButton")
            self.horizontalLayout_4.addWidget(self.toolButton)
            self.toolButton_12 = QtWidgets.QToolButton(self.tab_2)
            self.toolButton_12.setObjectName("toolButton_12")
            self.horizontalLayout_4.addWidget(self.toolButton_12)
            self.toolButton_2 = QtWidgets.QToolButton(self.tab_2)
            self.toolButton_2.setObjectName("toolButton_2")
            self.horizontalLayout_4.addWidget(self.toolButton_2)
            self.toolButton_3 = QtWidgets.QToolButton(self.tab_2)
            self.toolButton_3.setObjectName("toolButton_3")
            self.horizontalLayout_4.addWidget(self.toolButton_3)
            self.verticalLayout.addLayout(self.horizontalLayout_4)
            self.horizontalLayout = QtWidgets.QHBoxLayout()
            self.horizontalLayout.setObjectName("horizontalLayout")
            self.label_11 = QtWidgets.QLabel(self.tab_2)
            self.label_11.setObjectName("label_11")
            self.horizontalLayout.addWidget(self.label_11)
            self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_2)
            self.lineEdit_3.setObjectName("lineEdit_3")
            self.horizontalLayout.addWidget(self.lineEdit_3)
            self.label_10 = QtWidgets.QLabel(self.tab_2)
            self.label_10.setText("")
            self.label_10.setObjectName("label_10")
            self.horizontalLayout.addWidget(self.label_10)
            self.toolButton_6 = QtWidgets.QToolButton(self.tab_2)
            self.toolButton_6.setObjectName("toolButton_6")
            self.horizontalLayout.addWidget(self.toolButton_6)
            self.verticalLayout.addLayout(self.horizontalLayout)
            self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
            self.horizontalLayout_9.setObjectName("horizontalLayout_9")
            self.label_16 = QtWidgets.QLabel(self.tab_2)
            self.label_16.setObjectName("label_16")
            self.horizontalLayout_9.addWidget(self.label_16)
            self.label_17 = QtWidgets.QLabel(self.tab_2)
            self.label_17.setObjectName("label_17")
            self.horizontalLayout_9.addWidget(self.label_17)
            self.verticalLayout.addLayout(self.horizontalLayout_9)
            spacerItem1 = QtWidgets.QSpacerItem(218, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
            self.horizontalLayout_9.addItem(spacerItem1)
            self.treeWidget = QtWidgets.QTreeWidget(self.tab_2)
            self.treeWidget.setObjectName("treeWidget")
            self.verticalLayout.addWidget(self.treeWidget)
            self.tabWidget.addTab(self.tab_2, "")
            self.tab = QtWidgets.QWidget()
            self.tab.setObjectName("tab")
            self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
            self.verticalLayout_2.setObjectName("verticalLayout_2")
            self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
            self.horizontalLayout_5.setObjectName("horizontalLayout_5")
            self.comboBox = QtWidgets.QComboBox(self.tab)
            self.comboBox.setObjectName("comboBox")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.horizontalLayout_5.addWidget(self.comboBox)
            self.lineEdit = QtWidgets.QLineEdit(self.tab)
            self.lineEdit.setObjectName("lineEdit")
            self.horizontalLayout_5.addWidget(self.lineEdit)
            self.toolButton_4 = QtWidgets.QToolButton(self.tab)
            self.toolButton_4.setObjectName("toolButton_4")
            self.horizontalLayout_5.addWidget(self.toolButton_4)
            self.verticalLayout_2.addLayout(self.horizontalLayout_5)
            self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
            self.horizontalLayout_6.setObjectName("horizontalLayout_6")
            self.label_4 = QtWidgets.QLabel(self.tab)
            self.label_4.setObjectName("label_4")
            self.horizontalLayout_6.addWidget(self.label_4)
            self.toolButton_7 = QtWidgets.QToolButton(self.tab)
            self.toolButton_7.setObjectName("toolButton_7")
            self.horizontalLayout_6.addWidget(self.toolButton_7)
            self.toolButton_5 = QtWidgets.QToolButton(self.tab)
            self.toolButton_5.setObjectName("toolButton_5")
            self.horizontalLayout_6.addWidget(self.toolButton_5)
            self.verticalLayout_2.addLayout(self.horizontalLayout_6)
            self.treeWidget1 = QtWidgets.QTreeWidget(self.tab)
            self.treeWidget1.setObjectName("treeWidget1")
            self.verticalLayout_2.addWidget(self.treeWidget1)
            self.treeWidget1.setHeaderLabels(["文件","大小","作者","日期","MD5"])
            self.tabWidget.addTab(self.tab, "")
            self.tab_3 = QtWidgets.QWidget()
            self.tab_3.setObjectName("tab_3")
            self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_3)
            self.gridLayout_2.setObjectName("gridLayout_2")
            self.label_5 = QtWidgets.QLabel(self.tab_3)
            self.label_5.setObjectName("label_5")
            self.gridLayout_2.addWidget(self.label_5, 2, 5, 1, 1)
            spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
            self.gridLayout_2.addItem(spacerItem2, 2, 1, 1, 1)
            self.progressBar = QtWidgets.QProgressBar(self.tab_3)
            self.progressBar.setProperty("value", 24)
            self.progressBar.setObjectName("progressBar")
            self.gridLayout_2.addWidget(self.progressBar, 2, 4, 1, 1)
            spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
            self.gridLayout_2.addItem(spacerItem3, 2, 3, 1, 1)
            spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
            self.gridLayout_2.addItem(spacerItem4, 2, 2, 1, 1)
            spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
            self.gridLayout_2.addItem(spacerItem5, 2, 0, 1, 1)
            self.label_6 = QtWidgets.QLabel(self.tab_3)
            self.label_6.setObjectName("label_6")
            self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
            self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_3)
            self.tableWidget_2.setObjectName("tableWidget_2")
            self.tableWidget_2.setColumnCount(6)
            self.tableWidget_2.setRowCount(1)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_2.setVerticalHeaderItem(0, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_2.setHorizontalHeaderItem(0, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_2.setHorizontalHeaderItem(1, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_2.setHorizontalHeaderItem(2, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_2.setHorizontalHeaderItem(3, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_2.setHorizontalHeaderItem(4, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_2.setHorizontalHeaderItem(5, item)
            self.tableWidget_2.horizontalHeader().setSortIndicatorShown(True)
            self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
            self.tableWidget_2.verticalHeader().setCascadingSectionResizes(True)
            self.tableWidget_2.verticalHeader().setSortIndicatorShown(True)
            self.tableWidget_2.verticalHeader().setStretchLastSection(False)
            self.gridLayout_2.addWidget(self.tableWidget_2, 1, 0, 1, 6)
            self.tabWidget.addTab(self.tab_3, "")
            self.tab_4 = QtWidgets.QWidget()
            self.tab_4.setObjectName("tab_4")
            self.gridLayout = QtWidgets.QGridLayout(self.tab_4)
            self.gridLayout.setObjectName("gridLayout")
            self.label_9 = QtWidgets.QLabel(self.tab_4)
            self.label_9.setObjectName("label_9")
            self.gridLayout.addWidget(self.label_9, 2, 1, 1, 1)
            self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_4)
            self.lineEdit_2.setObjectName("lineEdit_2")
            self.gridLayout.addWidget(self.lineEdit_2, 0, 1, 1, 1)
            spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
            self.gridLayout.addItem(spacerItem6, 1, 2, 1, 1)
            self.label_7 = QtWidgets.QLabel(self.tab_4)
            self.label_7.setObjectName("label_7")
            self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
            self.label_8 = QtWidgets.QLabel(self.tab_4)
            self.label_8.setObjectName("label_8")
            self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
            self.pushButton_2 = QtWidgets.QPushButton(self.tab_4)
            self.pushButton_2.setObjectName("pushButton_2")
            self.gridLayout.addWidget(self.pushButton_2, 0, 2, 1, 1)
            self.verticalLayout_4 = QtWidgets.QVBoxLayout()
            self.verticalLayout_4.setObjectName("verticalLayout_4")
            self.pushButton_3 = QtWidgets.QPushButton(self.tab_4)
            self.pushButton_3.setObjectName("pushButton_3")
            self.verticalLayout_4.addWidget(self.pushButton_3)
            self.pushButton_4 = QtWidgets.QPushButton(self.tab_4)
            self.pushButton_4.setObjectName("pushButton_4")
            self.verticalLayout_4.addWidget(self.pushButton_4)
            self.gridLayout.addLayout(self.verticalLayout_4, 2, 2, 1, 1)
            spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
            self.gridLayout.addItem(spacerItem7, 3, 2, 1, 1)
            self.tabWidget.addTab(self.tab_4, "")
            self.tab_5 = QtWidgets.QWidget()
            self.tab_5.setObjectName("tab_5")
            self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_5)
            self.gridLayout_3.setObjectName("gridLayout_3")
            self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
            self.horizontalLayout_3.setObjectName("horizontalLayout_3")
            self.label_12 = QtWidgets.QLabel(self.tab_5)
            self.label_12.setObjectName("label_12")
            self.horizontalLayout_3.addWidget(self.label_12)
            self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_5)
            self.lineEdit_4.setObjectName("lineEdit_4")
            self.horizontalLayout_3.addWidget(self.lineEdit_4)
            self.label_13 = QtWidgets.QLabel(self.tab_5)
            self.label_13.setObjectName("label_13")
            self.horizontalLayout_3.addWidget(self.label_13)
            self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_5)
            self.lineEdit_5.setObjectName("lineEdit_5")
            self.horizontalLayout_3.addWidget(self.lineEdit_5)
            self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
            self.treeWidget_2 = QtWidgets.QTreeWidget(self.tab_5)
            self.treeWidget_2.setObjectName("treeWidget_2")
            self.gridLayout_3.addWidget(self.treeWidget_2, 2, 1, 1, 1)
            self.treeWidget.setHeaderLabels(["文件","大小","日期","类型"])
            self.treeWidget_2.setHeaderLabels(["文件","大小","作者","日期","MD5"])
            self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
            self.horizontalLayout_7.setObjectName("horizontalLayout_7")
            self.label_14 = QtWidgets.QLabel(self.tab_5)
            self.label_14.setObjectName("label_14")
            self.horizontalLayout_7.addWidget(self.label_14)
            self.toolButton_8 = QtWidgets.QToolButton(self.tab_5)
            self.toolButton_8.setObjectName("toolButton_8")
            self.horizontalLayout_7.addWidget(self.toolButton_8)
            self.toolButton_9 = QtWidgets.QToolButton(self.tab_5)
            self.toolButton_9.setObjectName("toolButton_9")
            self.horizontalLayout_7.addWidget(self.toolButton_9)
            self.gridLayout_3.addLayout(self.horizontalLayout_7, 1, 1, 1, 1)
            self.tabWidget.addTab(self.tab_5, "")
            self.tab_6 = QtWidgets.QWidget()
            self.tab_6.setObjectName("tab_6")
            self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_6)
            self.gridLayout_4.setObjectName("gridLayout_4")
            self.groupBox_2 = QtWidgets.QGroupBox(self.tab_6)
            self.groupBox_2.setObjectName("groupBox_2")
            self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
            self.gridLayout_6.setObjectName("gridLayout_6")
            spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
            self.gridLayout_6.addItem(spacerItem8, 2, 0, 1, 1)
            self.tableWidget_3 = QtWidgets.QTableWidget(self.groupBox_2)
            self.tableWidget_3.setObjectName("tableWidget_3")
            self.tableWidget_3.setColumnCount(3)
            self.tableWidget_3.setRowCount(1)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_3.setVerticalHeaderItem(0, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_3.setVerticalHeaderItem(1, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_3.setVerticalHeaderItem(2, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_3.setVerticalHeaderItem(3, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_3.setVerticalHeaderItem(4, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_3.setVerticalHeaderItem(5, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_3.setVerticalHeaderItem(6, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_3.setVerticalHeaderItem(7, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_3.setVerticalHeaderItem(8, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_3.setVerticalHeaderItem(9, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_3.setHorizontalHeaderItem(0, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_3.setHorizontalHeaderItem(1, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_3.setHorizontalHeaderItem(2, item)
            self.tableWidget_3.horizontalHeader().setSortIndicatorShown(False)
            self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
            self.gridLayout_6.addWidget(self.tableWidget_3, 4, 0, 1, 3)
            self.toolButton_13 = QtWidgets.QToolButton(self.groupBox_2)
            self.toolButton_13.setObjectName("toolButton_13")
            self.gridLayout_6.addWidget(self.toolButton_13, 2, 1, 1, 1)
            self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
            self.horizontalLayout_10.setObjectName("horizontalLayout_10")
            self.label_18 = QtWidgets.QLabel(self.groupBox_2)
            self.label_18.setObjectName("label_18")
            self.horizontalLayout_10.addWidget(self.label_18)
            self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_2)
            self.lineEdit_7.setObjectName("lineEdit_7")
            self.horizontalLayout_10.addWidget(self.lineEdit_7)
            self.toolButton_14 = QtWidgets.QToolButton(self.groupBox_2)
            self.toolButton_14.setObjectName("toolButton_14")
            self.horizontalLayout_10.addWidget(self.toolButton_14)
            self.gridLayout_6.addLayout(self.horizontalLayout_10, 0, 0, 1, 3)
            self.label_19 = QtWidgets.QLabel(self.groupBox_2)
            self.label_19.setObjectName("label_19")
            self.gridLayout_6.addWidget(self.label_19, 3, 0, 1, 1)
            spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
            self.gridLayout_6.addItem(spacerItem9, 2, 2, 1, 1)
            self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
            self.horizontalLayout_11.setObjectName("horizontalLayout_11")
            self.label_20 = QtWidgets.QLabel(self.groupBox_2)
            self.label_20.setObjectName("label_20")
            self.horizontalLayout_11.addWidget(self.label_20)
            self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_2)
            self.lineEdit_8.setObjectName("lineEdit_8")
            self.horizontalLayout_11.addWidget(self.lineEdit_8)
            self.toolButton_15 = QtWidgets.QToolButton(self.groupBox_2)
            self.toolButton_15.setObjectName("toolButton_15")
            self.horizontalLayout_11.addWidget(self.toolButton_15)
            self.gridLayout_6.addLayout(self.horizontalLayout_11, 1, 0, 1, 3)
            self.gridLayout_4.addWidget(self.groupBox_2, 1, 0, 1, 1)
            self.groupBox = QtWidgets.QGroupBox(self.tab_6)
            self.groupBox.setObjectName("groupBox")
            self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
            self.gridLayout_5.setObjectName("gridLayout_5")
            self.toolButton_11 = QtWidgets.QToolButton(self.groupBox)
            self.toolButton_11.setObjectName("toolButton_11")
            self.gridLayout_5.addWidget(self.toolButton_11, 1, 1, 1, 1)
            self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
            self.tableWidget.setObjectName("tableWidget")
            self.tableWidget.setColumnCount(5)
            self.tableWidget.setRowCount(1)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setVerticalHeaderItem(0, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setHorizontalHeaderItem(0, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setHorizontalHeaderItem(1, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setHorizontalHeaderItem(2, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setHorizontalHeaderItem(3, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setHorizontalHeaderItem(4, item)
            self.tableWidget.horizontalHeader().setStretchLastSection(True)
            self.tableWidget.verticalHeader().setMinimumSectionSize(10)
            self.gridLayout_5.addWidget(self.tableWidget, 2, 0, 1, 2)
            self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
            self.horizontalLayout_8.setObjectName("horizontalLayout_8")
            self.label_15 = QtWidgets.QLabel(self.groupBox)
            self.label_15.setObjectName("label_15")
            self.horizontalLayout_8.addWidget(self.label_15)
            self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox)
            self.lineEdit_6.setObjectName("lineEdit_6")
            self.horizontalLayout_8.addWidget(self.lineEdit_6)
            self.toolButton_10 = QtWidgets.QToolButton(self.groupBox)
            self.toolButton_10.setObjectName("toolButton_10")
            self.horizontalLayout_8.addWidget(self.toolButton_10)
            self.gridLayout_5.addLayout(self.horizontalLayout_8, 0, 0, 1, 2)
            spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
            self.gridLayout_5.addItem(spacerItem10, 1, 0, 1, 1)
            self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
            self.tabWidget.addTab(self.tab_6, "")
            self.verticalLayout_3.addWidget(self.tabWidget)
            MainWindow.setCentralWidget(self.centralwidget)
            self.statusbar = QtWidgets.QStatusBar(MainWindow)
            self.statusbar.setObjectName("statusbar")
            MainWindow.setStatusBar(self.statusbar)
            self.retranslateUi(MainWindow)
            self.tabWidget.setCurrentIndex(0)
            QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
            def a(f):
                def wrapper(*args, **kwargs):
                    thr = Thread(target=f, args=args, kwargs=kwargs)
                    thr.start()

                return wrapper
            with open(getpath()+"\\py\\lib\\setting.json","r") as j:
                b=json.load(j)
                b=b["maindownload"]
            self.lineEdit_2.setText(b)
            @a
            def tw(self):
                with open(getpath()+"\\py\\lib\\tmp.json") as f:
                    j=json.load(f)
                    j["text"]=""
                with open(getpath()+"\\py\\lib\\tmp.json","w") as f:
                    json.dump(j,f)
                os.system(getpath()+"\\python38\\pythonw.exe "+getpath()+"\\py\\lib\\tweet.py")
            def ex():
                with open(getpath()+"\\py\\lib\\setting.json","r") as f:
                    j=json.load(f)
                    j["isLogin"]=0
                    j["cookie"]=""
                    j["username"]=""
                with open(getpath()+"\\py\\lib\\setting.json","w") as f:
                    json.dump(j,f)
                zt()
            @a
            def lo():
                os.system(getpath()+"\\python38\\pythonw.exe "+getpath()+"\\py\\lib\\DxLogin.py")
                if dl.islogin():
                    self.label_2.setText(_translate("MainWindow", dl.getname()))
                    self.pushButton_10.setVisible(True)
                    self.pushButton_10.setText("退出登录")
                else:
                    self.label_2.setText(_translate("MainWindow", "未登录"))
                    self.pushButton_10.setVisible(False)
                if dl.islogin():
                    self.pushButton.setText(_translate("MainWindow", "切换账号"))
                else:
                    self.pushButton.setText(_translate("MainWindow", "账号登录"))
            def twi():
                with open(getpath()+"\\py\\lib\\setting.json","r") as j:
                    b=json.load(j)
                    b["maindownload"]=self.lineEdit_2.text()
                with open(getpath()+"\\py\\lib\\setting.json","w") as j:
                    json.dump(b,j)
            def browse():
                Folderpath = QFileDialog.getExistingDirectory()
                self.lineEdit_2.setText(Folderpath)
            def cr():
                def msg5(self):
                    QMessageBox.about(self,"版权声明","Dxdownload V0.0.1beta\n该软件使用PyQt5和Python3编写。\n完全免费开源,无任何捐赠。\n由于该软件破解了百度网盘的官方机制,\n仅可用于学习交流使用,\n不步PanDownload后尘，谨慎使用并尽量支持正版!")
                msg5(MainWindow)
            def version():
                os.system(getpath()+"\\python38\\pythonw.exe "+getpath()+r"\py\lib\version.py")
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "Dxdownload"))
            MainWindow.setWindowIcon(QIcon(getpath()+r"\icon\Dx.ico"))
            self.label.setText(_translate("MainWindow", "<html><head/><body><p>Dxdownload          <span style=\" font-size:16pt;\">度盘不限速工具</span></p></body></html>"))
            def zt():
                if dl.islogin():
                    self.label_2.setText(_translate("MainWindow", dl.getname()))
                    self.pushButton_10.setVisible(True)
                    self.pushButton_10.setText("退出登录")
                else:
                    self.label_2.setText(_translate("MainWindow", "未登录"))
                    self.pushButton_10.setVisible(False)
                if dl.islogin():
                    self.pushButton.setText(_translate("MainWindow", "切换账号"))
                else:
                    self.pushButton.setText(_translate("MainWindow", "账号登录"))
            zt()
            self.pushButton_10.clicked.connect(lambda:ex())
            self.pushButton.clicked.connect(lambda :lo())
            self.tweetb.setText(_translate("MainWindow","反馈"))
            self.tweetb.clicked.connect(tw)
            self.label_3.setText(_translate("MainWindow", "操作:"))
            self.toolButton.setText(_translate("MainWindow", "下载"))
            self.reload.setText(_translate("MainWindow", "刷新"))
            self.toolButton_12.setText(_translate("MainWindow", "打包下载"))
            self.toolButton_2.setText(_translate("MainWindow", "分享"))
            self.toolButton_3.setText(_translate("MainWindow", "提取链接"))
            self.label_11.setText(_translate("MainWindow", "搜索："))
            self.toolButton_6.setText(_translate("MainWindow", "搜索"))
            self.label_16.setPixmap(QPixmap(getpath()+r"\icon\disk.ico"))
            self.label_17.setText(_translate("MainWindow", "我的网盘\\"))
            self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "文件"))
            self.lineEdit_2.textChanged.connect(lambda:twi())
            self.comboBox.setItemText(0, _translate("MainWindow", "盘多多"))
            self.comboBox.setItemText(1, _translate("MainWindow", "史莱姆"))
            self.comboBox.setItemText(2, _translate("MainWindow", "盘搜搜"))
            self.comboBox.setItemText(3, _translate("MainWindow", "吾爱破解"))
            self.toolButton_4.setText(_translate("MainWindow", "🔍"))
            self.label_4.setText(_translate("MainWindow", "结果:"))
            self.toolButton_7.setText(_translate("MainWindow", "下载"))
            self.toolButton_5.setText(_translate("MainWindow", "转存"))
            self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "搜索"))
            self.label_5.setText(_translate("MainWindow", "0kb/s"))
            self.label_6.setText(_translate("MainWindow", "正在下载:"))
            item = self.tableWidget_2.horizontalHeaderItem(0)
            item.setText(_translate("MainWindow", "文件"))
            item = self.tableWidget_2.horizontalHeaderItem(1)
            item.setText(_translate("MainWindow", "大小"))
            item = self.tableWidget_2.horizontalHeaderItem(2)
            item.setText(_translate("MainWindow", "进度"))
            item = self.tableWidget_2.horizontalHeaderItem(3)
            item.setText(_translate("MainWindow", "MD5"))
            item = self.tableWidget_2.horizontalHeaderItem(4)
            item.setText(_translate("MainWindow", "剩余时间"))
            item = self.tableWidget_2.horizontalHeaderItem(5)
            item.setText(_translate("MainWindow", "操作"))
            self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "下载"))
            self.label_9.setText(_translate("MainWindow", "<html><head/><body><p>copyright©2020 LYX                Dxdownload </p><p>使用Python3.8.4编写 完全免费开源</p><p><br/></p></body></html>"))
            self.label_7.setText(_translate("MainWindow", "默认下载路径:"))
            self.label_8.setText(_translate("MainWindow", "关于"))
            self.pushButton_2.setText(_translate("MainWindow", "浏览"))
            self.pushButton_2.clicked.connect(lambda:browse())
            self.pushButton_3.setText(_translate("MainWindow", "更新日志"))
            self.pushButton_3.clicked.connect(lambda:version())
            self.pushButton_4.setText(_translate("MainWindow", "版权声明"))
            self.pushButton_4.clicked.connect(lambda:cr())
            self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "设置"))
            self.label_12.setText(_translate("MainWindow", "链接;"))
            self.label_13.setText(_translate("MainWindow", "提取码："))
            
            self.label_14.setText(_translate("MainWindow", "操作："))
            self.toolButton_8.setText(_translate("MainWindow", "下载"))
            self.toolButton_9.setText(_translate("MainWindow", "转存"))
            self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "分享链接"))
            self.groupBox_2.setTitle(_translate("MainWindow", "上传"))
            item = self.tableWidget_3.verticalHeaderItem(0)
            item.setText(_translate("MainWindow", "1"))
            item = self.tableWidget_3.horizontalHeaderItem(0)
            item.setText(_translate("MainWindow", "文件名"))
            item = self.tableWidget_3.horizontalHeaderItem(1)
            item.setText(_translate("MainWindow", "大小"))
            item = self.tableWidget_3.horizontalHeaderItem(2)
            item.setText(_translate("MainWindow", "进度"))
            self.toolButton_13.setText(_translate("MainWindow", "上传"))
            self.label_18.setText(_translate("MainWindow", "选择文件："))
            self.toolButton_14.setText(_translate("MainWindow", "浏览"))
            self.label_19.setText(_translate("MainWindow", "进度："))
            self.label_20.setText(_translate("MainWindow", "上传路径："))
            self.toolButton_15.setText(_translate("MainWindow", "浏览"))
            self.groupBox.setTitle(_translate("MainWindow", "离线下载"))
            self.toolButton_11.setText(_translate("MainWindow", "转存到网盘"))
            item = self.tableWidget.verticalHeaderItem(0)
            item.setText(_translate("MainWindow", "文件"))
            item = self.tableWidget.horizontalHeaderItem(0)
            item.setText(_translate("MainWindow", "文件名"))
            item = self.tableWidget.horizontalHeaderItem(1)
            item.setText(_translate("MainWindow", "大小"))
            item = self.tableWidget.horizontalHeaderItem(2)
            item.setText(_translate("MainWindow", "MD5"))
            item = self.tableWidget.horizontalHeaderItem(3)
            item.setText(_translate("MainWindow", "SHA1"))
            item = self.tableWidget.horizontalHeaderItem(4)
            item.setText(_translate("MainWindow", "转存进度"))
            self.label_15.setText(_translate("MainWindow", "键入http/ftp/ed2k链接"))
            self.toolButton_10.setText(_translate("MainWindow", "打开"))
            self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "其它"))
    def main():
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
    if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
        main()
except SystemExit:
    pass
except:
    e=traceback.format_exc()
    print(e)
    err.error(e)